In [1]:
import pandas as pd
from pyprojroot import here
data = pd.read_csv(here() / 'data/raw/data.csv', parse_dates=True, index_col='datetime')

drop_these = ['Beds:HC_10', 
              'Beds:HC_11_(Ward_01)',
              'Beds:HC_11_(Ward_02)',
              'Beds:HC_11_(Ward_03)',
              'Beds:UH_(Ward_01)',
              'Beds:UH_(Ward_02)',
              'Beds:HC_14',
              'Beds:RH_B_(Ward_01)',
              'Beds:RH_B_(Ward_02)'
              ]

data = data.drop(columns=drop_these)
mask = data.columns.str.startswith('Beds')
hospitals = data.loc[:,mask]
missing = hospitals.isna().sum().sort_values()
hours = hospitals.values.flatten().shape
hours
missing.sum()
missing.sum() / hours
proportional = missing / hospitals.shape[0]
pd.concat([missing, proportional], axis=1)

                        0         1
Beds:HC_15              0  0.000000
Beds:HC_06              0  0.000000
Beds:RH_A_(Ward_02)     0  0.000000
Beds:HC_09              0  0.000000
Beds:RH_A_(Ward_11)     0  0.000000
Beds:RH_A_(Ward_04)     0  0.000000
Beds:RH_A_(Ward_10)     0  0.000000
Beds:HC_05              0  0.000000
Beds:HC_02           2004  0.092778
Beds:RH_A_(Ward_07)  2373  0.109861
Beds:RH_A_(Ward_01)  2373  0.109861
Beds:RH_A_(Ward_03)  4101  0.189861
Beds:RH_A_(Ward_09)  4101  0.189861
Beds:RH_A_(Ward_08)  4101  0.189861
Beds:RH_A_(Ward_06)  4101  0.189861
Beds:RH_A_(Ward_05)  4101  0.189861
Beds:HC_08           4101  0.189861
Beds:UH_(ED_ward)    4388  0.203148
Beds:HC_01           6499  0.300880
Beds:HC_12           6499  0.300880
Beds:HC_13           6823  0.315880
Beds:HC_04           7125  0.329861
Beds:HC_03           7460  0.345370
Beds:HC_07           7486  0.346574